steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/backend:latest'
      - '-f'
      - 'infrastructure/docker/backend.Dockerfile'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/backend:latest']
  
  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/frontend:latest'
      - '-f'
      - 'infrastructure/docker/frontend.Dockerfile'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/frontend:latest']
  
  # Run database migrations as a job
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'django-migrations'
      - '--region'
      - 'europe-west4'
      - '--wait'
    allowFailure: true

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gym-backend'
      - '--image'
      - 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/backend:latest'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MONGO_URI=mongodb+srv://Firas:kVgxCQ0M0nGyrOqS@cluster0.zsqjugz.mongodb.net/macroscanner?appName=Cluster0,SECRET_KEY=${_SECRET_KEY}'
  
  # Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gym-frontend'
      - '--image'
      - 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/frontend:latest'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/backend:latest'
  - 'europe-west4-docker.pkg.dev/gymx3-494520/gym-repo/frontend:latest'